config/routes.rb
Rails.application.routes.draw do
  resources :reports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
	has_attached_file :pdf, :styles => {:thumb => ["100x100>", :png], :xls => ["", :xls]}
  validates_attachment_content_type :pdf, :content_type => ['application/pdf']
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    var = `echo '#{@report.pdf}' | sed 's/^.*\?//'`
    `echo '#{@report.pdf}' | sed 's/\?.*$// ; s/^/public/' > pdf_'#{var}'`
    `echo '#{@report.pdf(:xls)}' | sed 's/\?.*$// ; s/^/public/' > xls_'#{var}' ; paste -d ' ' pdf_'#{var}' xls_'#{var}' > file_'#{var}'`
    system("pdf=`cat pdf_'#{var}'` ; pdftotext -q -layout $pdf")
    system("txt=`cat pdf_'#{var}' | sed 's/\.pdf$//'` ; sed 's/'\f'// ; s/   \+/  /g ; s/  /\t/g ; s/\t/\",\"/g ; s/^/\"/ ; s/$/\"/' $txt.txt > $txt.csv")
    system("xls=`cat pdf_'#{var}' | sed 's/\.pdf$//'` ; ssconvert $xls.csv  $xls.xls > /dev/null ; rm -f $xls.txt $xls.csv ")
    system("file=`cat file_'#{var}' | sed 's/^/mv / ; s/\.pdf /\.xls /' > file_'#{var}'.sh` ; chmod 775 file_'#{var}'.sh ; ./file_'#{var}'.sh")
    `rm -f rm -f file_'#{var}'.sh file_'#{var}' pdf_'#{var}' xls_'#{var}'`
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:investor_id, :pdf)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PdfToExls</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :investor_id %>
    <%= form.text_field :investor_id, id: :report_investor_id %>
  </div>

  <div class="field">
    <%= form.label :uploadPDF %><br>
    <%= form.file_field :pdf %>
  </div>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Investor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.investor_id %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Investor:</strong>
  <%= @report.investor_id %>
  <%= image_tag @report.pdf.url(:thumb) %>
  <%= link_to "View", @report.pdf.url %>  
  <%= link_to "Download(xls)", @report.pdf.url(:xls) %>

</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>